packages:
  - apps/*
  - packages/*

allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': true
  prisma: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - wikipoke@0.3.1
